name = "Stranbo"
uuid = "2cbcc540-60d5-4e59-8d77-8826b4db9639"
authors = ["gvdr <me@gvdallariva.net>"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
